apiVersion: v1
kind: Service
metadata:
  name: postgres-boilerbase-svc
  namespace: boilerbase
  labels:
    app: postgres-boilerbase
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: postgres-boilerbase