apiVersion: v1
kind: Service
metadata:
  name: boilerbase-api-svc
  namespace: boilerbase
spec:
  type: ClusterIP
  selector:
    app: boilerbase-api
  ports:
    - protocol: 'TCP'
      port: 3000
      targetPort: 3000