apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: boilerbase-api-certificate
  namespace: boilerbase
spec:
  # certificats wildcard
  dnsNames:
    - 'api.super-sympa.fr'

  issuerRef:
    kind: ClusterIssuer
    name: boilerbase-webapp-selfsigned-issuer #notre issuer
  # Secret pour stocker les certificats
  secretName: boilerbase-api-certificate-cert-secret-tls