name: deploy_vue

on:
  push:
    branches:
      - main
      - dev

jobs:
  build_and_push:
    name: Build Docker image and push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - id: commit
        uses: prompt/actions-commit-hash@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: tang0ch4rlie/boilerbaseapi:${{ steps.commit.outputs.short }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  deploy:
    name: Deploy to Kubernetes Cluster
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - id: commit
        uses: prompt/actions-commit-hash@v3
      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
      #      - name: Replace Image Label
      #        run: sed -i'' -e 's/IMAGE_LABEL/${{ steps.commit.outputs.short }}/g' ".github/k8s/vue-deployment.yaml"
      - name: Deploy to the Kubernetes cluster
        uses: azure/k8s-deploy@v1
        with:
          namespace: boilerbase
          manifests: |
            .github/k8s/nestjs/api-deployment.yaml
            .github/k8s/nestjs/api-ingress.yaml
            .github/k8s/nestjs/api-service.yaml
          images: |
            tang0ch4rlie/boilerbaseapi:${{ steps.commit.outputs.short }}
#      - name: Deploy to Cluster
#        run: kubectl apply -f ".github/k8s/vue-deployment.yaml"